namespace Reveal.Sdk.Dom.Visualizations
{
    public enum ChartType
    {
        Column,
        Line,
        Bar,
        Area,
        Spline,
        SplineArea,
        StepArea,
        StepLine,
        Composite,
        Bubble,
        Candlestick,
        OHLC,
        Pie,
        RadialLines,
        RadialColumns,
        RadialPie,
        Scatter,
        PolarArea,
        PolarLines,
        PolarScatter,
        StackedColumn,
        StackedArea,
        StackedBar,
        Doughnut,
        Funnel,
        TimeSeries
    }
}
